sudo: required

services:
  - docker

language: node_js
node_js:
  - "6"

env:
  global:
    - ACUITY_SERVER_VERSION=0.1.0
    - SERVER_IMG=entake/acuity-server
    - SERVER_TEST_IMG=$SERVER_IMG:$ACUITY_SERVER_VERSION-debug
    - SERVER_RELEASE_IMG=$SERVER_IMG:$ACUITY_SERVER_VERSION
    - REPORT_COVERAGE="bash <(curl -s https://codecov.io/env)"

before_install:
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

install:
  - docker build --pull -t $SERVER_TEST_IMG ./server

script:
  - docker run $SERVER_TEST_IMG npm run test-ci

after_success:
  - docker run $SERVER_TEST_IMG $REPORT_COVERAGE
  - if [ "$TRAVIS_BRANCH" != "master" ]; then docker push "$SERVER_TEST_IMG"; fi

deploy:
  provider: script
  script: util/deploy.sh
  on:
    branch: master

notifications:
  email: false
