sudo: required

services:
  - docker

language: node_js
node_js:
  - "6.9.1"

env:
  global:
    - SERVER_DEBUG_IMG=entake/acuity-server:0.3.0-debug
    - SERVER_RELEASE_IMG=entake/acuity-server:0.3.0
    - CLIENT_DEBUG_IMG=entake/acuity-client:0.3.0-debug
    - CLIENT_RELEASE_IMG=entake/acuity-client:0.3.0

before_install:
  - npm list -g yarn --depth=0 || npm install -g yarn
  - npm config set loglevel warn # When using npm install, only print errors/warnings

install:
  - cd $TRAVIS_BUILD_DIR/server && npm i
  - cd $TRAVIS_BUILD_DIR/client && yarn

script:
  - cd $TRAVIS_BUILD_DIR/server && npm run test-ci && npm run lint
  - cd $TRAVIS_BUILD_DIR/client && npm run lint

after_success:
  - cd $TRAVIS_BUILD_DIR/server && bash <(curl -s https://codecov.io/bash) # Report coverage to Codecov
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD # Login to Docker Hub
  - docker build -t $SERVER_DEBUG_IMG $TRAVIS_BUILD_DIR/server # Build server debug image
  - cd $TRAVIS_BUILD_DIR/client && npm run build # TEMP - Builds client bundle
  - docker build -t $CLIENT_DEBUG_IMG $TRAVIS_BUILD_DIR/client # Build client debug image
  - if [ "$TRAVIS_BRANCH" != "master" ]; then docker push "$SERVER_DEBUG_IMG"; fi # Push server debug image to registry except on master
  - if [ "$TRAVIS_BRANCH" != "master" ]; then docker push "$CLIENT_DEBUG_IMG"; fi # Push client debug image to registry except on master

deploy:
  provider: script
  script: $TRAVIS_BUILD_DIR/util/deploy.sh
  on:
    branch: master

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0f7b075e8d4317a32d00
    on_success: change
    on_failure: always
    on_start: never
