sudo: required

services:
  - docker

language: node_js
node_js:
  - "6"

env:
  global:
      - SERVER_TEST_IMG=entake/acuity-server:build-$TRAVIS_JOB_NUMBER
      - SERVER_RELEASE_IMG=entake/acuity-server:latest

before_install:
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

install:
  - docker build --pull -t $SERVER_TEST_IMG ./server

script:
  - docker run $SERVER_TEST_IMG nyc npm test && nyc report --reporter=text-lcov | coveralls

after_success:
  - docker push $SERVER_TEST_IMG

deploy:
  provider: script
  script: docker tag $SERVER_TEST_IMG $SERVER_RELEASE_IMG && docker push $SERVER_RELEASE_IMG
  on:
    branch: master
