sudo: required

services:
  - docker

language: node_js
node_js:
  - "6.9.1"

env:
  global:
    - ACUITY_SERVER_VERSION=0.1.0
    - ACUITY_CLIENT_VERSION=0.1.0
    - SERVER_DEBUG_IMG=entake/acuity-server:$ACUITY_SERVER_VERSION-debug
    - SERVER_RELEASE_IMG=entake/acuity-server:$ACUITY_SERVER_VERSION
    - CLIENT_DEBUG_IMG=entake/acuity-client:$ACUITY_CLIENT_VERSION-debug
    - CLIENT_RELEASE_IMG=entake/acuity-server:$ACUITY_CLIENT_VERSION

cache:
  directories:
    - $TRAVIS_BUILD_DIR/server/node_modules
    - $(npm config get prefix)/bin/yarn

before_install:
  - npm list -g yarn --depth=0 || npm install -g yarn

install:
  - cd $TRAVIS_BUILD_DIR/server && yarn
  - cd $TRAVIS_BUILD_DIR/client && yarn

script:
  - cd $TRAVIS_BUILD_DIR/server && npm run test-ci && npm run lint
  - cd $TRAVIS_BUILD_DIR/client && npm run lint

after_success:
  - cd $TRAVIS_BUILD_DIR/server && bash <(curl -s https://codecov.io/bash) # Report coverage to Codecov
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD # Login to Docker Hub
  - docker build -t $SERVER_DEBUG_IMG $TRAVIS_BUILD_DIR/server # Build server debug image
  - docker build -t $CLIENT_DEBUG_IMG $TRAVIS_BUILD_DIR/client # Build client debug image
  - if [ "$TRAVIS_BRANCH" != "master" ]; then docker push "$SERVER_DEBUG_IMG"; fi # Push server debug image to registry except on master
  - if [ "$TRAVIS_BRANCH" != "master" ]; then docker push "$CLIENT_DEBUG_IMG"; fi # Push client debug image to registry except on master

deploy:
  provider: script
  script: $TRAVIS_BUILD_DIR/util/deploy.sh
  on:
    branch: master

notifications:
  email: false
